# Site settings
title: Modern Slavery Statements
tag_text: modern slavery statements
description: Biscuit is a single-page responsive Jekyll theme. This is the most simple and still-good-looking Jekyll theme that you can find.
baseurl: ""
url: "https://modernslaverystatements.com"

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
